var lodash = require('lodash'),
    rAF = require('../vendor/rAF'),
    jquery = require('jquery'),
    jqueryEasing = require('jquery.easing/js/jquery.easing.min.js'),
    jqueryScrollTo = require('scrollTo'),
    // bootstrap = require('bootstrap'),
    bsModal = require('bootstrap/js/modal.js'),
    bsToolTip = require('bootstrap/js/tooltip.js'),
    bsCarousel = require('bootstrap/js/carousel.js'),
    bsCollapse = require('bootstrap/js/collapse.js'),
    bsScrollSpy = require('bootstrap/js/scrollspy.js'),
    snackBar = require('snackbarjs/dist/snackbar.min'),
    angular = require('angular'),
    angularResource = require ('angularResource'),
    angularRoute = require('angularRoute'),
    angularSanitize = require('angularSanitize'),
    // angularTranslate = require('angularTranslate'),
    angularGoogleMaps = require('angularGoogleMaps'),
    tweenLite = require('gsap/src/minified/TweenLite.min.js'),
    easePack = require('gsap/src/minified/easing/EasePack.min.js'),
    // angularFamous = require('angularFamous'),
    viewer = require('viewer');

// lodash.noConflict();
// jquery.noConflict(true);
